-- MySQL Script generated by MySQL Workbench
-- 11/20/14 12:16:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDIC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDIC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDIC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BDIC` ;

-- -----------------------------------------------------
-- Table `BDIC`.`node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`node` (
  `idNODE` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `INFORMACOES` VARCHAR(45) NULL,
  PRIMARY KEY (`idNODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`datasource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`datasource` (
  `idESTACAO_METEO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_ESTACAO` VARCHAR(45) NULL,
  `FABRICANTE` VARCHAR(45) NULL,
  `MODELO` VARCHAR(45) NULL,
  `node_idNODE` INT(11) NOT NULL,
  PRIMARY KEY (`idESTACAO_METEO`, `node_idNODE`),
  INDEX `fk_datasource_node_idx` (`node_idNODE` ASC),
  CONSTRAINT `fk_datasource_node`
    FOREIGN KEY (`node_idNODE`)
    REFERENCES `BDIC`.`node` (`idNODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`tag` (
  `idTAG` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_TAG` VARCHAR(45) NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `DESVIO` VARCHAR(45) NULL,
  `TEMPO_MAX` VARCHAR(45) NULL,
  `datasource_idESTACAO_METEO` INT(11) NOT NULL,
  PRIMARY KEY (`idTAG`, `datasource_idESTACAO_METEO`),
  INDEX `fk_tag_datasource1_idx` (`datasource_idESTACAO_METEO` ASC),
  CONSTRAINT `fk_tag_datasource1`
    FOREIGN KEY (`datasource_idESTACAO_METEO`)
    REFERENCES `BDIC`.`datasource` (`idESTACAO_METEO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`valores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`valores` (
  `idValores` INT(11) NOT NULL AUTO_INCREMENT,
  `VALOR` VARCHAR(45) NULL,
  `DATAHORA` TIMESTAMP NULL,
  `tag_idTAG` INT(11) NOT NULL,
  `tag_datasource_idESTACAO_METEO` INT(11) NOT NULL,
  PRIMARY KEY (`idValores`, `tag_idTAG`, `tag_datasource_idESTACAO_METEO`),
  INDEX `fk_valores_tag1_idx` (`tag_idTAG` ASC, `tag_datasource_idESTACAO_METEO` ASC),
  CONSTRAINT `fk_valores_tag1`
    FOREIGN KEY (`tag_idTAG` , `tag_datasource_idESTACAO_METEO`)
    REFERENCES `BDIC`.`tag` (`idTAG` , `datasource_idESTACAO_METEO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`snapshot` (
  `idSNAP` INT(11) NOT NULL AUTO_INCREMENT,
  `VALOR` VARCHAR(45) NULL,
  `SNAPSHOT` TIMESTAMP NULL,
  `NOME_TAG` VARCHAR(45) NULL,
  `tag_idTAG` INT(11) NOT NULL,
  PRIMARY KEY (`idSNAP`, `tag_idTAG`),
  INDEX `fk_snapshot_tag1_idx` (`tag_idTAG` ASC),
  CONSTRAINT `fk_snapshot_tag1`
    FOREIGN KEY (`tag_idTAG`)
    REFERENCES `BDIC`.`tag` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
