-- MySQL Script generated by MySQL Workbench
-- 05/22/15 13:36:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDIC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDIC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDIC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BDIC` ;

-- -----------------------------------------------------
-- Table `BDIC`.`node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`node` (
  `idNODE` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `INFORMACOES` VARCHAR(45) NULL,
  PRIMARY KEY (`idNODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`datasource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`datasource` (
  `idESTACAO_METEO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME_ESTACAO` VARCHAR(45) NULL,
  `FABRICANTE` VARCHAR(45) NULL,
  `MODELO` VARCHAR(45) NULL,
  `node_idNODE` INT(11) NULL,
  PRIMARY KEY (`idESTACAO_METEO`),
  INDEX `fk_datasource_node1_idx` (`node_idNODE` ASC),
  CONSTRAINT `fk_datasource_node1`
    FOREIGN KEY (`node_idNODE`)
    REFERENCES `BDIC`.`node` (`idNODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`tagInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`tagInfo` (
  `idtagInfo` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  PRIMARY KEY (`idtagInfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`tag` (
  `idTAG` INT(11) NOT NULL AUTO_INCREMENT,
  `DESVIO` FLOAT NULL,
  `TEMPO_MAX` INT(11) NULL,
  `CONV_RATE` INT(11) NULL,
  `tagInfo_idtagInfo1` INT(11) NOT NULL,
  `datasource_idESTACAO_METEO` INT(11) NULL,
  PRIMARY KEY (`idTAG`),
  INDEX `fk_tag_tagInfo2_idx` (`tagInfo_idtagInfo1` ASC),
  INDEX `fk_tag_datasource1_idx` (`datasource_idESTACAO_METEO` ASC),
  CONSTRAINT `fk_tag_tagInfo2`
    FOREIGN KEY (`tagInfo_idtagInfo1`)
    REFERENCES `BDIC`.`tagInfo` (`idtagInfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_datasource1`
    FOREIGN KEY (`datasource_idESTACAO_METEO`)
    REFERENCES `BDIC`.`datasource` (`idESTACAO_METEO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`valores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`valores` (
  `idValores` INT(11) NOT NULL AUTO_INCREMENT,
  `VALOR` FLOAT NULL,
  `DATAHORA` TIMESTAMP NULL,
  `tag_idTAG` INT(11) NOT NULL,
  PRIMARY KEY (`idValores`),
  INDEX `fk_valores_tag1_idx` (`tag_idTAG` ASC),
  CONSTRAINT `fk_valores_tag1`
    FOREIGN KEY (`tag_idTAG`)
    REFERENCES `BDIC`.`tag` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`snapshot` (
  `idSNAP` INT(11) NOT NULL AUTO_INCREMENT,
  `VALOR` FLOAT NULL,
  `SNAPSHOT` TIMESTAMP NULL,
  `NOME_TAG` VARCHAR(45) NULL,
  `tag_idTAG` INT(11) NOT NULL,
  PRIMARY KEY (`idSNAP`),
  INDEX `fk_snapshot_tag1_idx` (`tag_idTAG` ASC),
  CONSTRAINT `fk_snapshot_tag1`
    FOREIGN KEY (`tag_idTAG`)
    REFERENCES `BDIC`.`tag` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`radioTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`radioTipo` (
  `idradioTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(300) NULL,
  PRIMARY KEY (`idradioTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDIC`.`radio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`radio` (
  `idradio` INT NOT NULL AUTO_INCREMENT,
  `endReal` VARCHAR(64) NULL,
  `radioTipo_idradioTipo` INT NOT NULL,
  `datasource_idESTACAO_METEO` INT(11) NULL,
  PRIMARY KEY (`idradio`),
  INDEX `fk_radio_radioTipo1_idx` (`radioTipo_idradioTipo` ASC),
  INDEX `fk_radio_datasource1_idx` (`datasource_idESTACAO_METEO` ASC),
  CONSTRAINT `fk_radio_radioTipo1`
    FOREIGN KEY (`radioTipo_idradioTipo`)
    REFERENCES `BDIC`.`radioTipo` (`idradioTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_radio_datasource1`
    FOREIGN KEY (`datasource_idESTACAO_METEO`)
    REFERENCES `BDIC`.`datasource` (`idESTACAO_METEO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `BDIC` ;

-- -----------------------------------------------------
-- Placeholder table for view `BDIC`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDIC`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `BDIC`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BDIC`.`view1`;
USE `BDIC`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
